name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: ga-test-project-503ca
  REGION: europe-west1
  GAR_LOCATION: europe-west1-docker.pkg.dev/ga-test-project-503ca/mtaylor-images/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build image
      run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}greenfieldbot
      working-directory: greenfield/

    - name: Push image
      run: docker push ${{ env.GAR_LOCATION }}